/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nist.pms;

/**
 *
 * @author Rishika Gupta
 */
public class Ownernewabout extends javax.swing.JPanel {

    /**
     * Creates new form Ownernewabout
     */
    public Ownernewabout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labrador = new javax.swing.JButton();
        boxer = new javax.swing.JButton();
        pug = new javax.swing.JButton();
        golden = new javax.swing.JButton();
        lasa = new javax.swing.JButton();
        german = new javax.swing.JButton();
        husky = new javax.swing.JButton();
        cookie = new javax.swing.JButton();

        setBackground(new java.awt.Color(96, 106, 116));

        labrador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labrador.setForeground(new java.awt.Color(0, 0, 0));
        labrador.setText("LABRADOR RETRIEVER");
        labrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labradorActionPerformed(evt);
            }
        });

        boxer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boxer.setForeground(new java.awt.Color(0, 0, 0));
        boxer.setText("BOXER");
        boxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxerActionPerformed(evt);
            }
        });

        pug.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pug.setForeground(new java.awt.Color(0, 0, 0));
        pug.setText("PUG");
        pug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pugActionPerformed(evt);
            }
        });

        golden.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        golden.setForeground(new java.awt.Color(0, 0, 0));
        golden.setText("GOLDEN RETRIEVER");
        golden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goldenActionPerformed(evt);
            }
        });

        lasa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lasa.setForeground(new java.awt.Color(0, 0, 0));
        lasa.setText("LASA APPSO");
        lasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lasaActionPerformed(evt);
            }
        });

        german.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        german.setForeground(new java.awt.Color(0, 0, 0));
        german.setText("GERMAN SHEPHERD");
        german.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                germanActionPerformed(evt);
            }
        });

        husky.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        husky.setForeground(new java.awt.Color(0, 0, 0));
        husky.setText("SIBERIAN HUSKY");
        husky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huskyActionPerformed(evt);
            }
        });

        cookie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cookie.setForeground(new java.awt.Color(0, 0, 0));
        cookie.setText("COCKER SPANIEL");
        cookie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cookieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labrador, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(golden, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxer, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pug, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cookie, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(husky, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(german, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lasa, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(golden, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(german, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labrador, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lasa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxer, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(husky, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pug, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cookie, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labradorActionPerformed
        // TODO add your handling code here:
        labrador l = new labrador();
        l.setVisible(true);
    }//GEN-LAST:event_labradorActionPerformed

    private void boxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxerActionPerformed
        // TODO add your handling code here:
        Boxer b = new Boxer();
        b.setVisible(true);
    }//GEN-LAST:event_boxerActionPerformed

    private void pugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pugActionPerformed
        // TODO add your handling code here:
         pug p = new pug();
        p.setVisible(true);
    }//GEN-LAST:event_pugActionPerformed

    private void goldenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goldenActionPerformed
        // TODO add your handling code here:
        Golden g = new Golden();
        g.setVisible(true);
    }//GEN-LAST:event_goldenActionPerformed

    private void lasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lasaActionPerformed
        // TODO add your handling code here:
        lasa la = new lasa();
        la.setVisible(true);
    }//GEN-LAST:event_lasaActionPerformed

    private void germanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_germanActionPerformed
        // TODO add your handling code here:
         german g = new german();
        g.setVisible(true);
    }//GEN-LAST:event_germanActionPerformed

    private void huskyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huskyActionPerformed
        // TODO add your handling code here:
        husky h = new husky();
        h.setVisible(true);
    }//GEN-LAST:event_huskyActionPerformed

    private void cookieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cookieActionPerformed
        // TODO add your handling code here:
        cookir c = new cookir();
        c.setVisible(true);
    }//GEN-LAST:event_cookieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boxer;
    private javax.swing.JButton cookie;
    private javax.swing.JButton german;
    private javax.swing.JButton golden;
    private javax.swing.JButton husky;
    private javax.swing.JButton labrador;
    private javax.swing.JButton lasa;
    private javax.swing.JButton pug;
    // End of variables declaration//GEN-END:variables
}
