/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nist.pms;

/**
 *
 * @author Rishika Gupta
 */

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Ownermanagepet extends javax.swing.JPanel {
    public Ownermanagepet() {
        initComponents();
         display();
         update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void update(){
        String sql = "SELECT * from petmanagmentsystem.veterinary";
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/petmanagmentsystem","root","nitch24");
          
            Statement stmt=conn.createStatement();
             ResultSet r = stmt.executeQuery(sql);
             while (r.next()){
              String name = r.getString("Firstname");
              vetnametext.addItem(name);
             }
             
            
        }
        catch(Exception e ){
        
        }
        
    }
     public void display(){
    try{
              Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petmanagmentsystem","root","nitch24");
            Statement stmt=con.createStatement();
             String sql ="select * from petmanagmentsystem.managepet";
             ResultSet rs = stmt.executeQuery(sql);
             while(rs.next()){
                
                 String pet_name = rs.getString("Petname");
                  String vet = rs.getString("Veterinary");
                   
                 String v1 = rs.getString("VaccineLastDate");
                   String v2 = rs.getString("VaccineNextDate");
                  String condition = rs.getString("Condition");
                  
                   
                   String tbData[]={pet_name,vet,v1,v2,condition};
                   
                   DefaultTableModel tbModel=(DefaultTableModel)table.getModel();
                   tbModel.addRow(tbData);
                   
                    
             }
             
         }
         catch(Exception ex){
             
         }  
}

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        petnametext = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        vaccine1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        condition1 = new javax.swing.JLabel();
        condi = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        vaccine2 = new com.toedter.calendar.JDateChooser();
        condition = new javax.swing.JLabel();
        booked = new javax.swing.JRadioButton();
        save = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        vetnametext = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(96, 106, 116));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Pet Information");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pet Name:");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vaccine last Date: ");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Veterinary Name:");

        condition1.setBackground(new java.awt.Color(0, 0, 0));
        condition1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        condition1.setForeground(new java.awt.Color(255, 255, 255));
        condition1.setText("Condition:");

        condi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Good", "Better", "Bad", "Worst" }));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vaccine Next Date: ");

        condition.setBackground(new java.awt.Color(0, 0, 0));
        condition.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        condition.setForeground(new java.awt.Color(255, 255, 255));
        condition.setText("Book Veterian:");

        booked.setBackground(new java.awt.Color(96, 106, 116));
        booked.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        booked.setForeground(new java.awt.Color(255, 255, 255));
        booked.setText("Booked");

        save.setBackground(new java.awt.Color(96, 106, 116));
        save.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Petname", "Veteran", "Last Date", "Next Date", "Condition"
            }
        ));
        jScrollPane3.setViewportView(table);

        vetnametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vetnametextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(condition1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(petnametext)
                    .addComponent(vaccine1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(condi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(condition, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(booked, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vaccine2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vetnametext, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 107, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(save))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(petnametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(vetnametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vaccine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vaccine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(condition1)
                    .addComponent(condi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(condition)
                    .addComponent(booked))
                .addGap(35, 35, 35)
                .addComponent(save)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:

        String petname = petnametext.getText();
        SimpleDateFormat dformat1  = new SimpleDateFormat("MMM dd yyyy");
        String v1 = dformat1.format(vaccine1.getDate());
        SimpleDateFormat dformat2  = new SimpleDateFormat("MMM dd yyyy");
        String v2= dformat2.format(vaccine2.getDate());
        String condition = (String)condi.getSelectedItem();
       
            
         if(vetnametext.getSelectedItem()==booked){
            System.out.println(booked.isSelected());
           // book ="Booked";
            
        }
        else{
            JOptionPane.showMessageDialog(null, "The Veteran is not available at the moment");

        }
       
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petmanagmentsystem","root","nitch24");
            Statement stmt=con.createStatement();
            stmt.executeUpdate("insert into petmanagmentsystem.managepet(PetName,Vetran,Last,Next,Condition,Book)values('"+petname+"','"+vetnametext+"','"+v1+"','"+v2+"','"+condition+"','"+booked+"')");
            JOptionPane.showMessageDialog(null, "Added Sucessfully");
            String sql ="select * from petmanagmentsystem.managepet";
            JOptionPane.showMessageDialog(null, "Added Sucessfully");

        } catch (Exception ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Error Adding");
        }

    }//GEN-LAST:event_saveActionPerformed

    private void vetnametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vetnametextActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_vetnametextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton booked;
    private javax.swing.JComboBox<String> condi;
    private javax.swing.JLabel condition;
    private javax.swing.JLabel condition1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField petnametext;
    private javax.swing.JButton save;
    private javax.swing.JTable table;
    private com.toedter.calendar.JDateChooser vaccine1;
    private com.toedter.calendar.JDateChooser vaccine2;
    private javax.swing.JComboBox<String> vetnametext;
    // End of variables declaration//GEN-END:variables
}
