/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nist.pms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishika Gupta
 */
public class Userlostfound extends javax.swing.JPanel {
ArrayList<byte[]> tableByte = null;
    public Userlostfound() {
        initComponents();
        SelectMoreinfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void SelectMoreinfo(){
     try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petmanagmentsystem","root","nitch24");
            Statement stmt=con.createStatement();
             String sql ="select * from petmanagmentsystem.lostandfound";
             ResultSet rs = stmt.executeQuery(sql);
             while(rs.next()){
                String id =String.valueOf(rs.getInt("id"));
               
                   String pet_name = rs.getString("Petname");
                    String color = rs.getString("Color");
                   String Age =String.valueOf(rs.getInt("Age"));
                    String d = rs.getString("Date");
                   String more = rs.getString("Moreinfo");
                  // String pic = rs.getString("Image");
                  byte[] picture = rs.getBytes("Image");
//                  Arrays.toString(picture);
                   String tbData[]={id,pet_name,color,Age,d,more};
                  
                  tableByte.add(picture);
                   DefaultTableModel tbModel=(DefaultTableModel)table.getModel();
                   tbModel.addRow(tbData);
             }
             
         }
         catch(Exception ex){
             
         }   
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setBackground(new java.awt.Color(180, 182, 182));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Lost and Found Information");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Petname", "Color", "Age", "MissingDate", "More Info"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        
       displaylostandfound  l = new displaylostandfound();
       l.setVisible(true);
       
      
        DefaultTableModel tblModel = (DefaultTableModel) table.getModel();

        //set data to text field
        String tblId = tblModel.getValueAt(table.getSelectedRow(), 0).toString();
        
        String tblpetname = tblModel.getValueAt(table.getSelectedRow(), 1).toString();
        String tblcolor = tblModel.getValueAt(table.getSelectedRow(), 2).toString();
        String tblage = tblModel.getValueAt(table.getSelectedRow(), 3).toString();
        String tbldate = tblModel.getValueAt(table.getSelectedRow(), 4).toString();
       
        System.out.println("Hello data"+tbldate);

        String tblmoreinfo = tblModel.getValueAt(table.getSelectedRow(), 5).toString();
        //String tblpic = tblModel.getValueAt(table.getSelectedRow(), 6).toString(); 
        //JOptionPane.showMessageDialog(null, tblMFD);
        java.util.Date M = null;

        try {
            M = new SimpleDateFormat("MMM dd yyyy").parse(tbldate);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
       // l.filetext.setText(tblpic);
        l.petnametext.setText(tblpetname);
        l.colortext.setText(tblcolor);
        l.agetext.setText(tblage);
        l.missing.setDate(M);
        l.moreinfotext.setText(tblmoreinfo);
    
    }//GEN-LAST:event_tableMouseClicked

  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
