/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nist.pms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishika Gupta
 */
public class UserVeterinaary extends javax.swing.JFrame {

    /**
     * Creates new form UserVeterinaary
     */
    public UserVeterinaary() {
        initComponents();
           SelectVet();
    }
    public void SelectVet(){
     try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petmanagmentsystem","root","nitch24");
            Statement stmt=con.createStatement();
             String sql ="select * from petmanagmentsystem.veterinary";
             ResultSet rs = stmt.executeQuery(sql);
             while(rs.next()){
                String id =String.valueOf(rs.getInt("id"));
                 String full_name = rs.getString("Firstname");
                   String last_name = rs.getString("Lastname");
                    String email = rs.getString("Email");
                    String add = rs.getString("Address");
                     String phone = rs.getString("phone");
                       String e = rs.getString("Experience");
                  
                    
               
                   String tbData[]={id,full_name,last_name,email,add,phone,e};
                   DefaultTableModel tbModel=(DefaultTableModel)table.getModel();
                   tbModel.addRow(tbData);
             }
             
         }
         catch(Exception ex){
             
         }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userbttn = new javax.swing.JButton();
        addmedicalinfo = new javax.swing.JButton();
        addpet = new javax.swing.JButton();
        petinformation = new javax.swing.JButton();
        lostfoundbttn = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 220, 171));

        userbttn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userbttn.setForeground(new java.awt.Color(108, 168, 183));
        userbttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nist/pms/icons8-user-40.png"))); // NOI18N
        userbttn.setText("User");
        userbttn.setBorder(null);
        userbttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userbttnMouseClicked(evt);
            }
        });
        userbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbttnActionPerformed(evt);
            }
        });

        addmedicalinfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addmedicalinfo.setForeground(new java.awt.Color(108, 168, 183));
        addmedicalinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nist/pms/icons8-vaccine-40.png"))); // NOI18N
        addmedicalinfo.setText("Add Medical Info");
        addmedicalinfo.setBorder(null);
        addmedicalinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmedicalinfoActionPerformed(evt);
            }
        });

        addpet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addpet.setForeground(new java.awt.Color(108, 168, 183));
        addpet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nist/pms/icons8-dog-35.png"))); // NOI18N
        addpet.setText("Add Pet");
        addpet.setBorder(null);
        addpet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpetActionPerformed(evt);
            }
        });

        petinformation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        petinformation.setForeground(new java.awt.Color(108, 168, 183));
        petinformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nist/pms/icons8-pet-35.png"))); // NOI18N
        petinformation.setText("Pet Information");
        petinformation.setBorder(null);
        petinformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petinformationActionPerformed(evt);
            }
        });

        lostfoundbttn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lostfoundbttn.setForeground(new java.awt.Color(108, 168, 183));
        lostfoundbttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nist/pms/icons8-alert-40.png"))); // NOI18N
        lostfoundbttn.setText("Lost And Found");
        lostfoundbttn.setBorder(null);
        lostfoundbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lostfoundbttnActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(108, 168, 183));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nist/pms/icons8-logout-25.png"))); // NOI18N
        logout.setText("Log out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(242, 220, 171));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 168, 183));
        jLabel1.setText(" System ");

        jLabel2.setBackground(new java.awt.Color(242, 220, 171));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(108, 168, 183));
        jLabel2.setText("Pet Managment");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nist/pms/icons8-dog-collar-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(petinformation, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addpet, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addmedicalinfo)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lostfoundbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3))
                            .addComponent(jLabel1))
                        .addGap(73, 73, 73))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(userbttn)
                .addGap(80, 80, 80)
                .addComponent(addpet, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(addmedicalinfo)
                .addGap(69, 69, 69)
                .addComponent(petinformation, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(lostfoundbttn)
                .addGap(70, 70, 70)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(482, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(180, 182, 182));
        content.setMaximumSize(new java.awt.Dimension(1123, 702));
        content.setMinimumSize(new java.awt.Dimension(1123, 702));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Other Veterinary  Information");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "First Name", "Last Name", "Email", "Phone No", "Address", "Experience"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Welcome to Pet Managment System");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nist/pms/pie.png"))); // NOI18N

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(412, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel4)
                .addGap(61, 61, 61)
                .addComponent(jLabel5)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    
    
  
    private void userbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbttnActionPerformed
        // TODO add your handling code here:
        Userveteran u = new Userveteran();
        u.setSize(1437, 1020);
        u.setLocation(0,0);
        
        content.removeAll();
        content.add(u);
        content.revalidate();
        content.repaint();
        
        
    
    }//GEN-LAST:event_userbttnActionPerformed

    private void addmedicalinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmedicalinfoActionPerformed
       
        Usermedicalinfo um = new Usermedicalinfo();
        um.setSize(1437, 1020);
        um.setLocation(0,0);
        
        content.removeAll();
        content.add(um);
        content.revalidate();
        content.repaint();
        
    }//GEN-LAST:event_addmedicalinfoActionPerformed

    private void addpetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpetActionPerformed
        // TODO add your handling code here:
       Useraddpet a = new Useraddpet();
        a.setSize(1437, 1020);
        a.setLocation(0,0);
        
        content.removeAll();
        content.add(a);
        content.revalidate();
        content.repaint();

    }//GEN-LAST:event_addpetActionPerformed

    private void petinformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petinformationActionPerformed
        // TODO add your handling code here:
      UserInformPet ip = new UserInformPet();
        ip.setSize(1437, 1020);
        ip.setLocation(0,0);
        
        content.removeAll();
        content.add(ip);
        content.revalidate();
        content.repaint();

    }//GEN-LAST:event_petinformationActionPerformed

    private void lostfoundbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lostfoundbttnActionPerformed
        // TODO add your handling code here:
       Userlostfound lf = new Userlostfound();
        lf.setSize(1437, 1020);
        lf.setLocation(0,0);
        
        content.removeAll();
        content.add(lf);
        content.revalidate();
        content.repaint();

    }//GEN-LAST:event_lostfoundbttnActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Are you sure you want to LOGOUT","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.out.println("Logout");
            this.dispose();
            new Veteranform().setVisible(true);

        }
    }//GEN-LAST:event_logoutActionPerformed

    private void userbttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbttnMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_userbttnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserVeterinaary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserVeterinaary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserVeterinaary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserVeterinaary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserVeterinaary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addmedicalinfo;
    private javax.swing.JButton addpet;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JButton lostfoundbttn;
    private javax.swing.JButton petinformation;
    private javax.swing.JTable table;
    private javax.swing.JButton userbttn;
    // End of variables declaration//GEN-END:variables
}
